### ISSUE TITLE
Pyramidal roof is skewed

### ISSUE THREAD

**Issue by kocio-pl** [kendzi/kendzi3d#48]
Kendzi3D 1.0.182 renders this pyramidal roof:

http://www.openstreetmap.org/way/315961631

as if it was skewed, while I expect it to have the peak in the centre of this polygon.

**Comment by blinkenlight** [comment]
I'd like to reconfirm this as a (fairly significant) bug. To be clear, I'm absolutely not trying to "criticise" or "blame" anyone or anything like that - I'd just like to get the point across that regardless of how exactly an algorithm might go about defining special cases for pyramidal (where differing interpretations might be possible), **no** algorithm can ever be called **adequate** if it fails to spot the pyramid center for those trivial cases where everyone would agree where it should be - in particular for shapes with simple symmetries, of which a rectangle is certainly the most common (and by far the most often used building shape). 

For such objects, the current algorithm places the center somewhere off to one "end" of the rectangle and I think it's safe to say that is **not** what anyone would expect for that shape. Again - I'm not arguing that pyramidal roofs with an off-to-a-side center might not exist in the real world: I'm asserting that even if they do, they're certainly the minority by a vast margin, therefore the current result is not the desirable one.

So here's an idea about how one might work around that (it's just a humble proposal of course): regardless of what algorithm is ultimately used for complicated cases, it should first check whether the points of the outline can be all fitted to a circle (which would be the one circumscribed around the outline of course, if it exists) - within a small margin of error obviously - and if so, it should use that circle's center as the center of the pyramid. This would take care of all simple-symmetry objects I can think of, like at-least-isosceles-triangular / square / rectangular / multi-side-circular shapes. By definition, this would not apply to non-convex shapes as those cannot fit on a circle, so one could keep using the current (or any other) interpretation for those.

**Comment by blinkenlight** [comment]
Sorry to follow up on my own post, but this has just occurred to me: **if** one wants to be extra fancy, even a few further simple-symmtery cases could be handled, out of those that would fail the "all points on the same circle" test - like a rhombus, a multi-side-ellipsoid or even an isosceles trapezoid (arguably, the last one would be better-served by testing with this criterion **before** the circle test - for everything else, the result would be identical anyway).

Specifically, one could fairly easily test for any outline made of "2n" (even) number of points whether all segments connecting points ("i, i+n" where 0<i<n-1) have their middle point in the (approximately) same point or not. If they do, that would fairly obviously be the center - and this should work fairly uncontroversially for any even-numbered convex object with some symmetry; objects with odd number of nodes (like a pentagon) would still need the outside-circle-test to get them right. However, the specific cases serviced (only) by this method are unusual shapes probably rarely encountered - which is why I suggest this only as an optional extra step...

**Comment by kendzi** [comment]
Maybe In that case best result will produce algorithm which calculate the smallest circle around building points?
https://en.wikipedia.org/wiki/Smallest-circle_problem
There is even some opensource implementation: https://github.com/hbf/miniball

**Comment by blinkenlight** [comment]
Yes, that certainly sounds good. For the shapes with some symmetry mentioned, that would be exactly identical with the circumscribed circle as proposed. That miniball lib sound perfect for this!

**Comment by kendzi** [comment]
I released version 1.0.185 with fix. Please check if its work.

**Comment by blinkenlight** [comment]
Thank you, pyramids are working now very nicely indeed.
